name: Movie Watcher

on:
  schedule:
    - cron: "0 * 8-18 3 *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: node --no-warnings check.js
      - run: node --no-warnings check_bms.js
