name: Movie Watcher

on:
  schedule:
    - cron: "0 * 8-18 3 *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--dns-result-order=ipv4first"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Run checks in parallel
        run: |
          node --no-warnings check.js &
          node --no-warnings check_bms.js &
          wait
